/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnalyzeMessageRouteImport } from './routes/analyze-message'
import { Route as AnalyzeUrlRouteImport } from './routes/analyze-url'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as ReportScamRouteImport } from './routes/report-scam'
import { Route as SafetyTipsRouteImport } from './routes/safety-tips'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeMessageRoute = AnalyzeMessageRouteImport.update({
  id: '/analyze-message',
  path: '/analyze-message',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeUrlRoute = AnalyzeUrlRouteImport.update({
  id: '/analyze-url',
  path: '/analyze-url',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportScamRoute = ReportScamRouteImport.update({
  id: '/report-scam',
  path: '/report-scam',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyTipsRoute = SafetyTipsRouteImport.update({
  id: '/safety-tips',
  path: '/safety-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze-message': typeof AnalyzeMessageRoute
  '/analyze-url': typeof AnalyzeUrlRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/report-scam': typeof ReportScamRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze-message': typeof AnalyzeMessageRoute
  '/analyze-url': typeof AnalyzeUrlRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/report-scam': typeof ReportScamRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analyze-message': typeof AnalyzeMessageRoute
  '/analyze-url': typeof AnalyzeUrlRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/report-scam': typeof ReportScamRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze-message'
    | '/analyze-url'
    | '/login'
    | '/lookup'
    | '/report-scam'
    | '/safety-tips'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze-message'
    | '/analyze-url'
    | '/login'
    | '/lookup'
    | '/report-scam'
    | '/safety-tips'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analyze-message'
    | '/analyze-url'
    | '/login'
    | '/lookup'
    | '/report-scam'
    | '/safety-tips'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalyzeMessageRoute: typeof AnalyzeMessageRoute
  AnalyzeUrlRoute: typeof AnalyzeUrlRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  ReportScamRoute: typeof ReportScamRoute
  SafetyTipsRoute: typeof SafetyTipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze-message': {
      id: '/analyze-message'
      path: '/analyze-message'
      fullPath: '/analyze-message'
      preLoaderRoute: typeof AnalyzeMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze-url': {
      id: '/analyze-url'
      path: '/analyze-url'
      fullPath: '/analyze-url'
      preLoaderRoute: typeof AnalyzeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-scam': {
      id: '/report-scam'
      path: '/report-scam'
      fullPath: '/report-scam'
      preLoaderRoute: typeof ReportScamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-tips': {
      id: '/safety-tips'
      path: '/safety-tips'
      fullPath: '/safety-tips'
      preLoaderRoute: typeof SafetyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalyzeMessageRoute: AnalyzeMessageRoute,
  AnalyzeUrlRoute: AnalyzeUrlRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  ReportScamRoute: ReportScamRoute,
  SafetyTipsRoute: SafetyTipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
